# Generated by Django 5.0 on 2024-09-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('tg_id', models.IntegerField(unique=True, verbose_name='Telegram id')),
                ('username', models.CharField(blank=True, db_index=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=50, null=True, verbose_name='Telegram username')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram full name')),
                ('user_full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='User full name')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel raqam')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.CharField(max_length=50, verbose_name='Fayl nomi')),
                ('description', models.TextField(default=' ', verbose_name='Fayl haqida')),
                ('file_url', models.FileField(upload_to='documents/', verbose_name='Fayl')),
            ],
            options={
                'verbose_name': 'Talaba hujjati',
                'verbose_name_plural': 'Talaba hujjatlari',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('academic_code', models.CharField(max_length=50, verbose_name='Guruh code')),
                ('kurs', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('para', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=50, verbose_name='Juftlik')),
                ('time_start', models.TimeField(default='08:30:00', verbose_name='Juftlik boshlanish vaqti')),
                ('time_end', models.TimeField(default='09:50:00', verbose_name='Juftlik tugash vaqti')),
            ],
            options={
                'verbose_name': 'Juftlik',
                'verbose_name_plural': 'Juftliklar',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('room', models.CharField(max_length=55, verbose_name="O'quv xonasi")),
                ('size', models.IntegerField(default=30, verbose_name="Xona o'lchami")),
                ('room_type', models.CharField(choices=[('Amaliyot', 'Amaliyot'), ("Ma'ruza", "Ma'ruza"), ('Laboratoriya', 'Laboratoriya')], default='Amaliyot', max_length=50, verbose_name='Xona turi')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('name', models.CharField(max_length=50, verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('name', models.CharField(max_length=50, verbose_name="F.I.O o'qituvchi")),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('subject', models.CharField(max_length=150, verbose_name='Sabab')),
                ('day', models.CharField(choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('Juma', 'Juma'), ('Shanba', 'Shanba')], default='Dushanba', max_length=50, verbose_name='Kun')),
                ('para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.para', verbose_name='Juftlik')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Xona bron qilish',
                'verbose_name_plural': 'Bron qilingan xonalar',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('lesson_type', models.CharField(choices=[('Amaliyot', 'Amaliyot'), ("Ma'ruza", "Ma'ruza"), ('Laboratoriya', 'Laboratoriya')], default='Amaliyot', max_length=50, verbose_name='Dars turi')),
                ('day', models.CharField(choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('Juma', 'Juma'), ('Shanba', 'Shanba')], default='Dushanba', max_length=50, verbose_name='Kun')),
                ('week', models.CharField(choices=[('full', 'full'), ('odd', 'odd'), ('even', 'even')], default='full', max_length=20, verbose_name='Hafta')),
                ('semester', models.CharField(choices=[('1', 'Kuzgi'), ('2', 'Bahorgi')], default='2', max_length=20, verbose_name='Semestr')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Guruh')),
                ('para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.para', verbose_name='Juftlik')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room', verbose_name='Xona')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Dars Jadvali',
                'verbose_name_plural': 'Dars Jadvali',
            },
        ),
    ]
