# Generated by Django 4.2.7 on 2024-03-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_schedule_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.CharField(choices=[('1', 'Kuzgi'), ('2', 'Bahorgi')], default='2', max_length=20, verbose_name='Semestr'),
        ),
    ]
