# Generated by Django 4.2.7 on 2024-03-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_schedule_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Dars Jadvali', 'verbose_name_plural': 'Dars Jadvali'},
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('cause', models.CharField(max_length=150, verbose_name='Sabab')),
                ('datetime_start', models.DateTimeField(auto_now=True, verbose_name='Boshlanish vaqti')),
                ('datetime_end', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room', verbose_name='Xona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
