# Generated by Django 4.2.7 on 2024-03-11 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_alter_bookingroom_datetime_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingroom',
            options={'verbose_name': 'Xona bron qilish', 'verbose_name_plural': 'Bron qilingan xonalar'},
        ),
        migrations.RemoveField(
            model_name='bookingroom',
            name='datetime_end',
        ),
        migrations.RemoveField(
            model_name='bookingroom',
            name='datetime_start',
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='day',
            field=models.CharField(choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('Juma', 'Juma'), ('Shanba', 'Shanba')], default='Dushanba', max_length=50, verbose_name='Kun'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='para',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.para', verbose_name='Juftlik'),
        ),
    ]
