# Generated by Django 4.2.7 on 2024-03-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_alter_bookingroom_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingroom',
            old_name='cause',
            new_name='subject',
        ),
    ]
